# SPDX-FileCopyrightText: 2025 RTE (https://www.rte-france.com)
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0

version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  jobs:
    install:
      - pip install --upgrade pip
      - pip install .
      - pip install --group docs

mkdocs:
  configuration: thermohl-docs/mkdocs.yml