package:
  name: thermohl
  version: "0.0.1"
about:
  home: https://gitlab.eurobios.com/rte/thermohl
  summary: thermohl is a python package for calculations relative to temperature in overhead conductors and their current intensity.
source:
  fn: thermohl-sprint_remi.tar.gz
  url: https://gitlab.eurobios.com/rte/thermohl/-/archive/sprint_remi/thermohl-sprint_remi.tar.gz
  md5: "56e302d6468f33f83e5011dc3508435b"

requirements:
  build:
    - pip >=19
    - python >=3.7
  run:
    - python >=3.7
    - numpy >= 1.19.0
    - pandas >= 1.1.3
    - scipy >= 1.5.2
    - matplotlib >= 3.7.1
    - pyyaml >= 5.3.1