#!/bin/bash

# -- dir for all envs
ENV_DIR=/home/${USER}/ENV
mkdir -p $ENV_DIR

# -- current env with link
VENV=${ENV_DIR}/thermohl
VLNK=.venv
ln -sf $VENV $VLNK
uv venv $VENV
source $VENV/bin/activate

# -- upgrade uv
uv self update

# -- install local package
cd ..
rm -rf build
uv pip install ".[examples,dev]"

# -- end text
echo "---"
echo -e "\e[1mto start the environment, type :\e[0m"
echo "source ${VENV}/bin/activate"
echo ""
echo -e "\e[1mto stop the environment, type :\e[0m"
echo "deactivate"
